// AI Blog - Main Application JavaScript
(function() {
    'use strict';

    // State management
    const state = {
        articles: [],
        currentView: 'home',
        currentArticle: null,
        theme: localStorage.getItem('theme') || 'light',
        likes: JSON.parse(localStorage.getItem('likes') || '{}')
    };

    // DOM Elements
    const elements = {
        contentArea: document.getElementById('contentArea'),
        articlesList: document.getElementById('articlesList'),
        searchInput: document.getElementById('searchInput'),
        modalSearchInput: document.getElementById('modalSearchInput'),
        searchModal: document.getElementById('searchModal'),
        searchResults: document.getElementById('searchResults'),
        tocSidebar: document.getElementById('tocSidebar'),
        tocContent: document.getElementById('tocContent'),
        breadcrumb: document.getElementById('breadcrumb'),
        themeToggle: document.getElementById('themeToggle'),
        menuToggle: document.getElementById('menuToggle'),
        sidebar: document.querySelector('.sidebar')
    };

    // Initialize application
    async function init() {
        applyTheme(state.theme);
        await loadArticles();
        setupEventListeners();
        renderHome();
    }

    // Load articles from pages directory
    async function loadArticles() {
        try {
            // Try to load articles.json first (generated by workflow)
            const response = await fetch('pages/articles.json');
            if (response.ok) {
                state.articles = await response.json();
            } else {
                // Fallback: scan for markdown files
                state.articles = await scanMarkdownFiles();
            }
            
            // Sort by date (newest first)
            state.articles.sort((a, b) => new Date(b.date) - new Date(a.date));
            
            updateSidebarNav();
        } catch (error) {
            console.error('Error loading articles:', error);
            state.articles = [];
        }
    }

    // Scan for markdown files (fallback method)
    async function scanMarkdownFiles() {
        // This is a fallback - in production, articles.json will be used
        const predefinedFiles = [
            'getting-started.md',
            'ai-future.md',
            'machine-learning-basics.md'
        ];
        
        const articles = [];
        for (const file of predefinedFiles) {
            try {
                const response = await fetch(`pages/${file}`);
                if (response.ok) {
                    const content = await response.text();
                    const article = parseMarkdownFrontmatter(content);
                    article.slug = file.replace('.md', '');
                    article.path = `pages/${file}`;
                    articles.push(article);
                }
            } catch (e) {
                // File doesn't exist, skip
            }
        }
        return articles;
    }

    // Parse frontmatter from markdown
    function parseMarkdownFrontmatter(content) {
        const frontmatterRegex = /^---\n([\s\S]*?)\n---\n([\s\S]*)/;
        const match = content.match(frontmatterRegex);
        
        let frontmatter = {};
        let body = content;
        
        if (match) {
            const frontmatterStr = match[1];
            body = match[2];
            
            // Parse YAML-like frontmatter
            frontmatterStr.split('\n').forEach(line => {
                const [key, ...valueParts] = line.split(':');
                if (key && valueParts.length) {
                    const value = valueParts.join(':').trim().replace(/^["']|["']$/g, '');
                    frontmatter[key.trim()] = value;
                }
            });
        }
        
        return {
            title: frontmatter.title || 'Untitled',
            description: frontmatter.description || '',
            date: frontmatter.date || new Date().toISOString().split('T')[0],
            author: frontmatter.author || 'AI Assistant',
            tags: frontmatter.tags ? frontmatter.tags.split(',').map(t => t.trim()) : [],
            body: body
        };
    }

    // Update sidebar navigation
    function updateSidebarNav() {
        elements.articlesList.innerHTML = state.articles.map(article => `
            <li>
                <a href="#" class="nav-item" data-slug="${article.slug}" data-view="article">
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M14 2H6C5.46957 2 4.96086 2.21071 4.58579 2.58579C4.21071 2.96086 4 3.46957 4 4V20C4 20.5304 4.21071 21.0391 4.58579 21.4142C4.96086 21.7893 5.46957 22 6 22H18C18.5304 22 19.0391 21.7893 19.4142 21.4142C19.7893 21.0391 20 20.5304 20 20V8L14 2Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M14 2V8H20" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    ${escapeHtml(article.title)}
                </a>
            </li>
        `).join('');

        // Add click handlers
        elements.articlesList.querySelectorAll('[data-view="article"]').forEach(item => {
            item.addEventListener('click', (e) => {
                e.preventDefault();
                const slug = item.getAttribute('data-slug');
                loadArticle(slug);
            });
        });
    }

    // Render home page
    function renderHome() {
        state.currentView = 'home';
        updateBreadcrumb(['Главная']);
        
        const recentArticles = state.articles.slice(0, 3);
        
        elements.contentArea.innerHTML = `
            <div class="home-hero">
                <h1>Добро пожаловать в AI Blog</h1>
                <p>Блог о технологиях, искусственном интеллекте и будущем, которое мы создаём вместе.</p>
                
                <div class="feature-cards">
                    <div class="feature-card">
                        <h3>📝 Markdown статьи</h3>
                        <p>Легко читаемый и пишущийся формат для документации и блогов</p>
                    </div>
                    <div class="feature-card">
                        <h3>❤️ Лайки</h3>
                        <p>Отмечайте понравившиеся статьи, они сохраняются в вашем браузере</p>
                    </div>
                    <div class="feature-card">
                        <h3>🔍 Поиск</h3>
                        <p>Быстрый поиск по всем статьям с помощью ⌘K или Ctrl+K</p>
                    </div>
                    <div class="feature-card">
                        <h3>🌓 Тёмная тема</h3>
                        <p>Переключайтесь между светлой и тёмной темой для комфорта глаз</p>
                    </div>
                </div>
            </div>
            
            ${recentArticles.length > 0 ? `
                <div style="margin-top: 60px;">
                    <h2 style="margin-bottom: 24px; font-size: 1.5rem;">Последние статьи</h2>
                    <div class="articles-grid">
                        ${recentArticles.map(article => createArticleCard(article)).join('')}
                    </div>
                </div>
            ` : ''}
            
            ${state.articles.length === 0 ? `
                <div class="empty-state" style="margin-top: 60px;">
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M14 2H6C5.46957 2 4.96086 2.21071 4.58579 2.58579C4.21071 2.96086 4 3.46957 4 4V20C4 20.5304 4.21071 21.0391 4.58579 21.4142C4.96086 21.7893 5.46957 22 6 22H18C18.5304 22 19.0391 21.7893 19.4142 21.4142C19.7893 21.0391 20 20.5304 20 20V8L14 2Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M14 2V8H20" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M12 18V12M12 12L10 14M12 12L14 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                    </svg>
                    <h3>Нет статей</h3>
                    <p>Добавьте .md файлы в папку pages/ чтобы они появились здесь</p>
                </div>
            ` : ''}
        `;

        updateActiveNavItem('home');
    }

    // Create article card HTML
    function createArticleCard(article) {
        const likeCount = state.likes[article.slug] || 0;
        const isLiked = state.likes[`liked_${article.slug}`] || false;
        
        return `
            <div class="article-card" data-slug="${article.slug}">
                <div class="article-card-header">
                    <span class="article-date">${formatDate(article.date)}</span>
                </div>
                <h2>${escapeHtml(article.title)}</h2>
                <p>${escapeHtml(article.description)}</p>
                <div class="article-meta">
                    <div class="article-tags">
                        ${article.tags.map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join('')}
                    </div>
                    <button class="like-btn ${isLiked ? 'liked' : ''}" data-slug="${article.slug}" onclick="event.stopPropagation(); toggleLike('${article.slug}')">
                        <svg viewBox="0 0 24 24" fill="${isLiked ? 'currentColor' : 'none'}" xmlns="http://www.w3.org/2000/svg">
                            <path d="M20.84 4.61C20.3292 4.099 19.7228 3.69364 19.0554 3.41708C18.3879 3.14052 17.6725 2.99817 16.95 2.99817C16.2275 2.99817 15.5121 3.14052 14.8446 3.41708C14.1772 3.69364 13.5708 4.099 13.06 4.61L12 5.67L10.94 4.61C9.9083 3.5783 8.50903 2.9987 7.05 2.9987C5.59096 2.9987 4.19169 3.5783 3.16 4.61C2.1283 5.64169 1.54871 7.04096 1.54871 8.5C1.54871 9.95903 2.1283 11.3583 3.16 12.39L4.22 13.45L12 21.23L19.78 13.45L20.84 12.39C21.351 11.8792 21.7563 11.2728 22.0329 10.6053C22.3095 9.93789 22.4518 9.22248 22.4518 8.5C22.4518 7.77751 22.3095 7.0621 22.0329 6.39469C21.7563 5.72728 21.351 5.12089 20.84 4.61V4.61Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <span>${likeCount}</span>
                    </button>
                </div>
            </div>
        `;
    }

    // Load and display article
    async function loadArticle(slug) {
        const article = state.articles.find(a => a.slug === slug);
        if (!article) return;

        state.currentView = 'article';
        state.currentArticle = article;

        try {
            const response = await fetch(article.path || `pages/${slug}.md`);
            const content = await response.text();
            const parsed = parseMarkdownFrontmatter(content);
            
            // Convert markdown to HTML
            const htmlContent = marked.parse(parsed.body);
            
            updateBreadcrumb(['Главная', 'Статьи', article.title]);
            
            elements.contentArea.innerHTML = `
                <div class="article-view">
                    <div class="article-header">
                        <h1 class="article-title">${escapeHtml(article.title)}</h1>
                        <div class="article-info">
                            <div class="article-author">
                                <div class="article-author-avatar">${article.author.charAt(0).toUpperCase()}</div>
                                <span>${escapeHtml(article.author)}</span>
                            </div>
                            <span class="article-date">${formatDate(article.date)}</span>
                            <button class="like-btn ${(state.likes[`liked_${slug}`]) ? 'liked' : ''}" onclick="toggleLike('${slug}')">
                                <svg viewBox="0 0 24 24" fill="${state.likes[`liked_${slug}`] ? 'currentColor' : 'none'}" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M20.84 4.61C20.3292 4.099 19.7228 3.69364 19.0554 3.41708C18.3879 3.14052 17.6725 2.99817 16.95 2.99817C16.2275 2.99817 15.5121 3.14052 14.8446 3.41708C14.1772 3.69364 13.5708 4.099 13.06 4.61L12 5.67L10.94 4.61C9.9083 3.5783 8.50903 2.9987 7.05 2.9987C5.59096 2.9987 4.19169 3.5783 3.16 4.61C2.1283 5.64169 1.54871 7.04096 1.54871 8.5C1.54871 9.95903 2.1283 11.3583 3.16 12.39L4.22 13.45L12 21.23L19.78 13.45L20.84 12.39C21.351 11.8792 21.7563 11.2728 22.0329 10.6053C22.3095 9.93789 22.4518 9.22248 22.4518 8.5C22.4518 7.77751 22.3095 7.0621 22.0329 6.39469C21.7563 5.72728 21.351 5.12089 20.84 4.61V4.61Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                                <span id="likeCount-${slug}">${state.likes[slug] || 0}</span>
                            </button>
                        </div>
                    </div>
                    <div class="article-body">
                        ${htmlContent}
                    </div>
                    <div class="article-footer">
                        <div class="article-tags">
                            ${article.tags.map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join('')}
                        </div>
                    </div>
                </div>
            `;

            // Generate TOC
            generateTOC(htmlContent);
            
            // Scroll to top
            window.scrollTo(0, 0);
            
            updateActiveNavItem('article', slug);
            
        } catch (error) {
            console.error('Error loading article:', error);
            elements.contentArea.innerHTML = `
                <div class="empty-state">
                    <h3>Ошибка загрузки</h3>
                    <p>Не удалось загрузить статью. Попробуйте позже.</p>
                </div>
            `;
        }
    }

    // Generate Table of Contents
    function generateTOC(htmlContent) {
        const parser = new DOMParser();
        const doc = parser.parseFromString(htmlContent, 'text/html');
        const headings = doc.querySelectorAll('h1, h2, h3');
        
        if (headings.length === 0) {
            elements.tocSidebar.style.display = 'none';
            return;
        }
        
        elements.tocSidebar.style.display = 'block';
        
        let tocHTML = '<ul>';
        headings.forEach((heading, index) => {
            const id = `heading-${index}`;
            heading.id = id;
            const level = heading.tagName.toLowerCase();
            const text = heading.textContent;
            tocHTML += `<li><a href="#${id}" class="toc-${level}">${escapeHtml(text)}</a></li>`;
        });
        tocHTML += '</ul>';
        
        elements.tocContent.innerHTML = tocHTML;
        
        // Add smooth scroll
        elements.tocContent.querySelectorAll('a').forEach(link => {
            link.addEventListener('click', (e) => {
                e.preventDefault();
                const target = document.querySelector(link.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
            });
        });
    }

    // Toggle like
    window.toggleLike = function(slug) {
        const likedKey = `liked_${slug}`;
        
        if (state.likes[likedKey]) {
            // Unlike
            state.likes[likedKey] = false;
            state.likes[slug] = Math.max(0, (state.likes[slug] || 0) - 1);
        } else {
            // Like
            state.likes[likedKey] = true;
            state.likes[slug] = (state.likes[slug] || 0) + 1;
        }
        
        localStorage.setItem('likes', JSON.stringify(state.likes));
        
        // Update UI
        const likeBtn = document.querySelector(`.like-btn[data-slug="${slug}"]`);
        const likeCountSpan = document.getElementById(`likeCount-${slug}`);
        
        if (likeBtn) {
            likeBtn.classList.toggle('liked');
            const svg = likeBtn.querySelector('svg');
            if (svg) {
                svg.setAttribute('fill', state.likes[likedKey] ? 'currentColor' : 'none');
            }
        }
        
        if (likeCountSpan) {
            likeCountSpan.textContent = state.likes[slug];
        }
        
        // Re-render if on home or all-posts view
        if (state.currentView === 'home' || state.currentView === 'all-posts') {
            if (state.currentView === 'home') renderHome();
            else renderAllPosts();
        }
    };

    // Render all posts view
    function renderAllPosts() {
        state.currentView = 'all-posts';
        updateBreadcrumb(['Главная', 'Все статьи']);
        
        elements.contentArea.innerHTML = `
            <div style="margin-bottom: 32px;">
                <h1 style="font-size: 2rem; margin-bottom: 8px;">Все статьи</h1>
                <p style="color: var(--text-secondary);">Всего статей: ${state.articles.length}</p>
            </div>
            <div class="articles-grid">
                ${state.articles.map(article => createArticleCard(article)).join('')}
            </div>
        `;
        
        updateActiveNavItem('all-posts');
    }

    // Search functionality
    function performSearch(query) {
        if (!query.trim()) {
            elements.searchResults.innerHTML = '';
            return;
        }
        
        const lowerQuery = query.toLowerCase();
        const results = state.articles.filter(article => 
            article.title.toLowerCase().includes(lowerQuery) ||
            article.description.toLowerCase().includes(lowerQuery) ||
            article.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
        );
        
        if (results.length === 0) {
            elements.searchResults.innerHTML = `
                <div class="empty-state" style="padding: 40px 20px;">
                    <p>Ничего не найдено</p>
                </div>
            `;
            return;
        }
        
        elements.searchResults.innerHTML = results.map(article => `
            <div class="search-result-item" data-slug="${article.slug}">
                <h4>${escapeHtml(article.title)}</h4>
                <p>${escapeHtml(article.description)}</p>
            </div>
        `).join('');
        
        // Add click handlers
        elements.searchResults.querySelectorAll('.search-result-item').forEach(item => {
            item.addEventListener('click', () => {
                const slug = item.getAttribute('data-slug');
                closeSearchModal();
                loadArticle(slug);
            });
        });
    }

    // Search modal controls
    function openSearchModal() {
        elements.searchModal.classList.add('active');
        elements.modalSearchInput.focus();
    }

    function closeSearchModal() {
        elements.searchModal.classList.remove('active');
        elements.modalSearchInput.value = '';
        elements.searchResults.innerHTML = '';
    }

    // Breadcrumb update
    function updateBreadcrumb(items) {
        elements.breadcrumb.innerHTML = items.map((item, index) => {
            if (index === items.length - 1) {
                return `<span style="color: var(--text-primary); font-weight: 500;">${escapeHtml(item)}</span>`;
            }
            return `<span>${escapeHtml(item)}</span> <span style="color: var(--text-tertiary);">/</span>`;
        }).join('');
    }

    // Update active nav item
    function updateActiveNavItem(view, slug = null) {
        document.querySelectorAll('.nav-item').forEach(item => {
            item.classList.remove('active');
            
            if (item.getAttribute('data-view') === view) {
                item.classList.add('active');
            }
            
            if (slug && item.getAttribute('data-slug') === slug) {
                item.classList.add('active');
            }
        });
    }

    // Theme management
    function applyTheme(theme) {
        state.theme = theme;
        localStorage.setItem('theme', theme);
        
        if (theme === 'dark') {
            document.documentElement.setAttribute('data-theme', 'dark');
        } else {
            document.documentElement.removeAttribute('data-theme');
        }
    }

    function toggleTheme() {
        applyTheme(state.theme === 'light' ? 'dark' : 'light');
    }

    // Setup event listeners
    function setupEventListeners() {
        // Navigation
        document.querySelectorAll('[data-view]').forEach(item => {
            item.addEventListener('click', (e) => {
                e.preventDefault();
                const view = item.getAttribute('data-view');
                
                if (view === 'home') renderHome();
                else if (view === 'all-posts') renderAllPosts();
            });
        });

        // Search
        elements.searchInput.addEventListener('click', openSearchModal);
        elements.modalSearchInput.addEventListener('input', (e) => {
            performSearch(e.target.value);
        });
        
        document.getElementById('closeSearch').addEventListener('click', closeSearchModal);
        
        elements.searchModal.querySelector('.search-modal-overlay').addEventListener('click', closeSearchModal);

        // Keyboard shortcuts
        document.addEventListener('keydown', (e) => {
            // Cmd/Ctrl + K for search
            if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
                e.preventDefault();
                openSearchModal();
            }
            
            // ESC to close search
            if (e.key === 'Escape' && elements.searchModal.classList.contains('active')) {
                closeSearchModal();
            }
        });

        // Theme toggle
        elements.themeToggle.addEventListener('click', toggleTheme);

        // Mobile menu toggle
        elements.menuToggle.addEventListener('click', () => {
            elements.sidebar.classList.toggle('active');
        });

        // Close mobile menu when clicking outside
        document.addEventListener('click', (e) => {
            if (window.innerWidth <= 768 && 
                !elements.sidebar.contains(e.target) && 
                !elements.menuToggle.contains(e.target) &&
                elements.sidebar.classList.contains('active')) {
                elements.sidebar.classList.remove('active');
            }
        });
    }

    // Utility functions
    function escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    function formatDate(dateStr) {
        const date = new Date(dateStr);
        return date.toLocaleDateString('ru-RU', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
    }

    // Start the application
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
